--- 
db:
  image: heimdallr/dhis2-trainingland-postgis-db 
  environment:
    - DB_USER=dhis
    - DB_PASS=dhis
    - DB_NAME=dhis
  volumes:
    - ./db-data:/var/lib/postgresql/data
tomcat: 
  image: heimdallr/tomcat-dhis2
  ports:
     - "8888:8080"
  links:
     - db:db
